name: Build React App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write # Permission for Action
jobs:
  build_react:
    runs-on: ubuntu-latest
    name: Build React
    steps:
      - uses: actions/checkout@v2
      - id: Build-React-App
        uses: BitDEVil2K16/ReactPagesAction@1.0.2
        with:
          username: "certifiedcodeboy"
          reponame: "main"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
